### ISSUE TITLE
谷歌浏览器跳出密码被泄露的提示,不知道是啥原因呢

### ISSUE THREAD

**Issue by anchuanyuan** [wuyawei/Vchat#11]
警告提示
![image](https://user-images.githubusercontent.com/36631774/80808213-a03db800-8bf1-11ea-8622-6ce61c06d8f5.png)

浏览器版本
![image](https://user-images.githubusercontent.com/36631774/80808257-b8153c00-8bf1-11ea-8948-0a8a5b222ead.png)

**Comment by Zhang275302472** [comment]
你是谁呀------------------ 原始邮件 ------------------
发件人: "anchuanyuan"<notifications@github.com>
发送时间: 2020年5月1日(星期五) 晚上9:21
收件人: "wuyawei/Vchat"<Vchat@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [wuyawei/Vchat] 谷歌浏览器跳出密码被泄露的提示,不知道是啥原因呢 (#11)




 
警告提示
 
 
浏览器版本
 
 
&mdash;
